version: '3.8'
services:
  flaggameapi:
    image: flaggameapi
    build:
      context: .
      dockerfile: MedDockerAPI/Dockerfile
    ports:
      - "7080:80"
      - "7081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "7081"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https-certs/your_cert.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "test"
    volumes:
      - ./certs:/https-certs:ro
    secrets:
      - cert-password
 
secrets:
  cert-password:
    external: true
